# ----------------------------------------------------------------------------------------------------------------------
#
#                                     _ __  ___       __                             __
#     _________  ____ ___  ____ ___  (_) /_/ (_)___  / /___________ __  ______ ___  / /
#    / ___/ __ \/ __ `__ \/ __ `__ \/ / __/ / / __ \/ __/ ___/ ___// / / / __ `__ \/ /
#  _/ /__/ /_/ / / / / / / / / / / / / /_/ / / / / / /_/ /  / /___/ /_/ / / / / / / /
# (_)___/\____/_/ /_/ /_/_/ /_/ /_/_/\__/_/_/_/ /_/\__/_/   \___(_)__, /_/ /_/ /_/_/
#                                                                 /____/
#
# For official documentation, see:
# https://commitlint.js.org/#/
#
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# PLUGINS
#
# Description:
# Exposes additional rules for use in commitlint
#
# For official documentation, see:
# https://commitlint.js.org/#/reference-plugins
#
# ----------------------------------------------------------------------------------------------------------------------

plugins:
  - commitlint-plugin-jira-rules

# ----------------------------------------------------------------------------------------------------------------------
# EXTENDS
#
# Description:
# Extend other commitlint configuration
#
# For official documentation, see:
# https://commitlint.js.org/#/reference-configuration?id=shareable-configuration
#
# ----------------------------------------------------------------------------------------------------------------------

extends:
  - jira

# ----------------------------------------------------------------------------------------------------------------------
# RULES
#
# Description:
# Override default or plugin rules
#
# For official documentation, see:
# https://commitlint.js.org/#/reference-rules
#
# ----------------------------------------------------------------------------------------------------------------------

rules:
  jira-task-id-max-length:
    - 2
    - always
    - 10
