# ----------------------------------------------------------------------------------------------------------------------
#
#                ___       __                             __
#     ___  _____/ (_)___  / /___________ __  ______ ___  / /
#    / _ \/ ___/ / / __ \/ __/ ___/ ___// / / / __ `__ \/ /
#  _/  __(__  ) / / / / / /_/ /  / /___/ /_/ / / / / / / /
# (_)___/____/_/_/_/ /_/\__/_/   \___(_)__, /_/ /_/ /_/_/
#                                     /____/
#
# For official documentation, see:
# https://eslint.org/docs/user-guide/configuring
#
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# PARSER
#
# Description:
# Specify parser that will allow ESLint to lint the code (by default ESLint expects ECMAScript 5 syntax)
#
# For official documentation, see:
# https://eslint.org/docs/user-guide/configuring#specifying-parser-options
#
# ----------------------------------------------------------------------------------------------------------------------

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2021
  sourceType: "module"
  ecmaFeatures:
    jsx: true
  project: tsconfig.json

# ----------------------------------------------------------------------------------------------------------------------
# SETTINGS
#
# Description:
# Specify settings which will be supplied to every rule that will be executed
#
# For official documentation, see:
# https://eslint.org/docs/user-guide/configuring#adding-shared-settings
#
# ----------------------------------------------------------------------------------------------------------------------

settings:
  import/resolver: node
  react:
    version: "detect"

# ----------------------------------------------------------------------------------------------------------------------
# ENVIRONMENTS
#
# Description:
# Specify environments in which the code was designed to run in
#
# For official documentation, see:
# https://eslint.org/docs/user-guide/configuring#specifying-environments
#
# ----------------------------------------------------------------------------------------------------------------------

env:
  browser: true
  node: true
  jest: true

#  ---------------------------------------------------------------------------------------------------------------------
#  PLUGINS
#
#  Description:
#  Specify plugins to load from $CWD/node_modules by default. Plugins can expose additional rules for use in ESLint
#
#  For official documentation, see:
#  https://eslint.org/docs/user-guide/configuring#configuring-plugins
#
#  ---------------------------------------------------------------------------------------------------------------------

plugins:
  - "@typescript-eslint"
  - import
  - jest
  - prettier

extends:
  - airbnb-typescript
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jest/recommended
  - plugin:jest/style
  - prettier
  - plugin:prettier/recommended

# ----------------------------------------------------------------------------------------------------------------------
# RULES
#
# Description:
# Specify which rules are enabled and at what error level
#
# For official documentation, see:
# https://eslint.org/docs/user-guide/configuring#configuring-rules
#
# ----------------------------------------------------------------------------------------------------------------------

rules:
  "import/no-named-as-default": "off"
  "react/jsx-props-no-spreading": "off"
  "no-underscore-dangle": "off"
  "@typescript-eslint/no-use-before-define": "off"
  "@typescript-eslint/lines-between-class-members": "off"
  "react/jsx-uses-react": "off"
  "react/react-in-jsx-scope": "off"
