# ----------------------------------------------------------------------------------------------------------------------
#
#       __               __                                    __
#      / /_  __  _______/ /____  ____________ __  ______ ___  / /
#     / __ \/ / / / ___/ //_/ / / / ___/ ___// / / / __ `__ \/ /
#  _ / / / / /_/ (__  ) ,< / /_/ / /  / /___/ /_/ / / / / / / /
# (_)_/ /_/\__,_/____/_/|_|\__, /_/   \___(_)__, /_/ /_/ /_/_/
#                         /____/           /____/
#
# For official documentation, see:
# https://github.com/typicode/husky
#
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# HOOKS
#
# Description:
# Specify which Git hooks to tap into
#
# For official documentation, see:
# https://github.com/typicode/husky#supported-hooks
#
# ----------------------------------------------------------------------------------------------------------------------

hooks:
  commit-msg: commitlint -E HUSKY_GIT_PARAMS
  pre-commit: lint-staged -v
