# ----------------------------------------------------------------------------------------------------------------------
#
#       ___       __       __                       __                           __
#      / (_)___  / /______/ /_____ _____ ____  ____/ /_________ __  ______ ___  / /
#     / / / __ \/ __/ ___/ __/ __ `/ __ `/ _ \/ __  / ___/ ___// / / / __ `__ \/ /
#  _ / / / / / / /_(__  ) /_/ /_/ / /_/ /  __/ /_/ / /  / /___/ /_/ / / / / / / /
# (_)_/_/_/ /_/\__/____/\__/\__,_/\__, /\___/\__,_/_/   \___(_)__, /_/ /_/ /_/_/
#                                /____/                      /____/
#
# For official documentation, see:
# https://github.com/okonet/lint-staged
#
# ----------------------------------------------------------------------------------------------------------------------

# ----------------------------------------------------------------------------------------------------------------------
# CONFIGURATION
#
# Description:
# Run commands on staged files defined by a glob pattern
#
# For official documentation, see:
# https://github.com/okonet/lint-staged#filtering-files
#
# ----------------------------------------------------------------------------------------------------------------------

"*.{js,ts,jsx,tsx}":
  - "eslint --fix"
  - jest --watchAll
